name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    env:
      VITE_FAT_SIGNER_API_URL: null
      VITE_FAT_DEV_PK: null
      VITE_GITHUB_SHA: ${{ github.sha }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Get Commit Date
        id: commit-date
        run: echo "date=$(TZ=UTC git log -1 --format=%cd --date='format-local:%Y-%m-%d %H:%M:%S')" >> "$GITHUB_OUTPUT"

      - name: Install npm dependencies
        run: npm install # switch to `ci` when Node.js 6.x is dropped

      - name: Build
        env:
          VITE_COMMIT_DATE: ${{ steps.commit-date.outputs.date }}
        run: npm run build

      - name: Deploy with gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"

